name: LinkCheck

on:
  push:
    branches: ['*']
    paths: ['Blocklist.txt']
  pull_request:
    paths: ['Blocklist.txt']
  workflow_dispatch:

jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker://dkhamsing/awesome_bot:latest
      with:
        args: /github/workspace/Blocklist.txt --allow-redirect
